/**
 * Every table, from both databases, in one import.
 *
 * Which client a table belongs to is not visible here — `projectSchema` tables
 * are queried with `db`, `agentSchema` tables with `agentDb`. Reach for the
 * wrong one and the query fails against a database that has no such table, so
 * the split is enforced at runtime rather than by convention.
 */

export {
  type AgentMemoryLong,
  type AiRecommendation,
  type AuditLog,
  agentMemoryLong,
  agentSchema,
  aiRecommendations,
  aiRecommendationsRelations,
  auditLogs,
  type BuildRequirements,
  buildRequirements,
  buildRequirementsRelations,
  type Conversation,
  type ConversationMessage,
  conversationMessages,
  conversationMessagesRelations,
  conversations,
  conversationsRelations,
  type Failure,
  failures,
  type NewAgentMemoryLong,
  type NewAiRecommendation,
  type NewAuditLog,
  type NewBuildRequirements,
  type NewConversation,
  type NewConversationMessage,
  type NewFailure,
  type NewReasoningLog,
  type ReasoningLog,
  reasoningLogs,
  reasoningLogsRelations,
} from "./agent";

export {
  type Account,
  type ApiKey,
  type ApiKeyMetadata,
  account,
  accountRelations,
  apikey,
  apikeyRelations,
  type Build,
  type BuildItem,
  buildItems,
  buildItemsRelations,
  builds,
  buildsRelations,
  type Campaign,
  type Cart,
  type CartItem,
  campaigns,
  campaignsRelations,
  cartItems,
  cartItemsRelations,
  carts,
  cartsRelations,
  type Inventory,
  inventory,
  inventoryRelations,
  type Merchant,
  merchants,
  merchantsRelations,
  type NewAccount,
  type NewApiKey,
  type NewBuild,
  type NewBuildItem,
  type NewCampaign,
  type NewCart,
  type NewCartItem,
  type NewInventory,
  type NewMerchant,
  type NewOrder,
  type NewOrderItem,
  type NewPayment,
  type NewProduct,
  type NewProductCategory,
  type NewProductSpec,
  type NewSession,
  type NewUser,
  type NewVerification,
  type Order,
  type OrderItem,
  orderItems,
  orderItemsRelations,
  orders,
  ordersRelations,
  type Payment,
  type PciePowerConnector,
  type Product,
  type ProductCategory,
  type ProductSpec,
  payments,
  paymentsRelations,
  productCategories,
  productCategoriesRelations,
  productSpecs,
  productSpecsRelations,
  products,
  productsRelations,
  projectSchema,
  type Session,
  session,
  sessionRelations,
  type User,
  user,
  userRelations,
  type Verification,
  verification,
} from "./project";
