/**
 * Every table, from both databases, in one import.
 *
 * Which client a table belongs to is not visible here — `projectSchema` tables
 * are queried with `db`, `agentSchema` tables with `agentDb`. Reach for the
 * wrong one and the query fails against a database that has no such table, so
 * the split is enforced at runtime rather than by convention.
 */

export { type Address, addresses, type NewAddress } from "./addresses";
export {
  type AgentFeedback,
  type AgentMemoryLong,
  type AgentTask,
  type AgentToolCall,
  type AiRecommendation,
  type AuditLog,
  agentFeedback,
  agentFeedbackRelations,
  agentMemoryLong,
  agentSchema,
  agentTasks,
  agentTasksRelations,
  agentToolCalls,
  agentToolCallsRelations,
  aiRecommendations,
  aiRecommendationsRelations,
  auditLogs,
  type BuildRequirements,
  buildRequirements,
  buildRequirementsRelations,
  type Conversation,
  type ConversationMessage,
  conversationMessages,
  conversationMessagesRelations,
  conversations,
  conversationsRelations,
  type Failure,
  failures,
  type NewAgentFeedback,
  type NewAgentMemoryLong,
  type NewAgentTask,
  type NewAgentToolCall,
  type NewAiRecommendation,
  type NewAuditLog,
  type NewBuildRequirements,
  type NewConversation,
  type NewConversationMessage,
  type NewFailure,
  type NewReasoningLog,
  type ReasoningLog,
  reasoningLogs,
  reasoningLogsRelations,
} from "./agent";

export {
  type Account,
  type ApiKey,
  type ApiKeyMetadata,
  account,
  accountRelations,
  apikey,
  apikeyRelations,
  type Build,
  type BuildItem,
  buildItems,
  buildItemsRelations,
  builds,
  buildsRelations,
  type BuyerMandate,
  type Campaign,
  type Cart,
  type CartItem,
  buyerMandates,
  campaigns,
  campaignsRelations,
  cartItems,
  cartItemsRelations,
  carts,
  cartsRelations,
  type Inventory,
  inventory,
  inventoryRelations,
  type Merchant,
  merchants,
  merchantsRelations,
  type NewAccount,
  type NewApiKey,
  type NewBuild,
  type NewBuildItem,
  type NewBuyerMandate,
  type NewCampaign,
  type NewCart,
  type NewCartItem,
  type NewInventory,
  type NewMerchant,
  type NewOrder,
  type NewOrderItem,
  type NewPayment,
  type NewProduct,
  type NewProductCategory,
  type NewProductSpec,
  type NewReorderRequest,
  type NewSession,
  type NewUser,
  type NewVerification,
  type Order,
  type OrderItem,
  orderItems,
  orderItemsRelations,
  orders,
  ordersRelations,
  type Payment,
  type PciePowerConnector,
  type MerchantPolicy,
  type Product,
  type ProductPriceChange,
  type ProductCategory,
  type ProductSpec,
  payments,
  paymentsRelations,
  productCategories,
  productCategoriesRelations,
  merchantPolicy,
  productPriceHistory,
  productSpecs,
  productSpecsRelations,
  products,
  productsRelations,
  projectSchema,
  type ReorderRequest,
  reorderRequests,
  reorderRequestsRelations,
  type Session,
  session,
  sessionRelations,
  type User,
  user,
  userRelations,
  type Verification,
  verification,
} from "./project";
